// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccszxrfoejayyftbajqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjc3p4cmZvZWpheXlmdGJhanFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNzcwMjQsImV4cCI6MjA1NDY1MzAyNH0.yZ48b8sABm947lk_jaeJh20tcQ2VQKZr38FkseiNULM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);